name: 🧪 Test Workflow

on:
    push:
        branches: [main]

jobs:
    setup:
        uses: ./.github/workflows/setup-node-pnpm.yml
        with:
            install: true
            fix: true
            test: true
            build: false
            check: false

    tests:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v4
            - run: echo "✅ Tests passed"
